DROP TABLE IF EXISTS users;

CREATE TABLE users (
  username VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS workspaces;

CREATE TABLE workspaces (
  wid INTEGER PRIMARY KEY AUTOINCREMENT,
  username VARCHAR(255) NOT NULL,
  FOREIGN KEY (username) REFERENCES users (username) ON DELETE CASCADE
);

DROP TABLE IF EXISTS workspaceTasks;

CREATE TABLE workspaceTasks (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  wid INTEGER NOT NULL,
  name VARCHAR(255) NOT NULL,
  detail VARCHAR(255) NOT NULL,
  assignedTo VARCHAR(255) NOT NULL,
  status VARCHAR(255) NOT NULL,
  FOREIGN KEY (wid) REFERENCES workspaces (wid) ON DELETE CASCADE
);